# fly.toml app configuration file generated for wispy-butterfly-7982 on 2023-08-27T03:02:57+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wispy-butterfly-7982"
primary_region = "hkg"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
